// Generated by Dagger (https://dagger.dev).
package te.app.evidence.pages.clients.notes.viewModels;

import dagger.MembersInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;
import te.app.evidence.repository.NotesRepository;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AddNoteViewModel_MembersInjector implements MembersInjector<AddNoteViewModel> {
  private final Provider<NotesRepository> notesRepositoryProvider;

  public AddNoteViewModel_MembersInjector(Provider<NotesRepository> notesRepositoryProvider) {
    this.notesRepositoryProvider = notesRepositoryProvider;
  }

  public static MembersInjector<AddNoteViewModel> create(
      Provider<NotesRepository> notesRepositoryProvider) {
    return new AddNoteViewModel_MembersInjector(notesRepositoryProvider);
  }

  @Override
  public void injectMembers(AddNoteViewModel instance) {
    injectNotesRepository(instance, notesRepositoryProvider.get());
  }

  @InjectedFieldSignature("te.app.evidence.pages.clients.notes.viewModels.AddNoteViewModel.notesRepository")
  public static void injectNotesRepository(AddNoteViewModel instance,
      NotesRepository notesRepository) {
    instance.notesRepository = notesRepository;
  }
}
